from Charmeleon import Charmeleon
from Charmander import Charmander
from Charizard import Charizard
from Pikachu import Pikachu
from Wartortle import Wartortle
from Blastoise import Blastoise
from Squirtle import Squirtle
from Trainer import Trainer
from Battle import Battle

# workcheck Charmander
# charmy = Charmander("charmy", 41, "fire", 6, 50, 54, 51)
# lst = charmy.get_effective_against_me()
# print(lst)
# lst[0] = "electric"
# print(lst)
# print(charmy.get_effective_against_me())
# print(charmy)

#workcheck charmeleon
# charmy = Charmander("charmy", 41, "fire", 6, 50, 54, 51)
# charmilious = Charmander("charmilious", 42, "fire", 13, 45, 55, 47)
# print(charmy)
# print(charmilious)
# print(charmilious.get_damage(charmy))
# charmilious.attack(charmy)
# print(charmy)
# print(charmilious)
# evolved_charmy = charmy.level_up(5)
# if evolved_charmy != None: charmy = evolved_charmy
# del evolved_charmy
# print(charmy)
# evolved_charmy = charmy.level_up(5)
# if evolved_charmy != None: charmy = evolved_charmy
# del evolved_charmy
# print(charmy)


#charizard work check
# charmilious = Charmander("charmilious", 42, "fire", 13, 45, 55, 47)
# charmander = charmilious.level_up(15)
# charizard = charmander.level_up(15)
# print(charizard)
# charizard.level_up(15)
# print(charizard)

#pikcchu workcheck
# pika = Pikachu("Pika",40,"electric",31,50,55,50,5)
# print(pika)
# pika.level_up(0)
# print(pika)
# poop = Charmander("poop", 40, "fire", 13,57,55,50)
# print(pika.get_damage(poop))

#squirtle check
# squirt = Squirtle("gay",40,"water",15,44,48,67)
# poop = Charmander("poop", 40, "fire", 13,57,55,50)
# print(squirt)
# print(poop)
# print(squirt.get_damage(poop))
# war = squirt.level_up(10)
# print(war)
# blast = war.level_up(15)
# print(blast)
# blast.level_up(2000)
# print(blast)
#
# poop = Charmander("poop", 40, "fire", 13,57,55,50)
# poopy = Charmander("poopy", 40, "fire", 15,57,55,50)
# # gay = Trainer("gay",17,11.0,[poop])

# warty = Wartortle("warty", 43, "water", 27, 65, 73, 90)
# pika = Pikachu("pika", 40, "electric", 19, 43, 60, 70, 3)
# print(pika.get_damage(warty))
# print(warty.get_damage(pika))
# ash = Trainer("Ash", 18, 3.,[pika,poop])
# mom = Trainer("mom", 18, 3.,[pika,poop,poopy, warty])
# ash2 = Trainer("Ash2", 18, 3.,[pika,warty])
# fag = ash + ash2
# blob = fag + mom
# print(fag)
# print(blob)


# ash.catch_pokemon(pika)
# print(ash)
# wort = Wartortle("warty", 41, "water", 20, 60, 70, 81)
# blast = wort.level_up(15)
# ash.catch_pokemon(blast)
# print(ash.total_hp())

# print(gay)
# gay.change_pokemon_lst(poopy,0)
# print(gay)
# gay.change_pokemon_lst(poop,0)
# print(gay)
# print(gay.get_age())
# print(gay.get_exp_modifier())
# print(gay.get_pokemon_lst())
# print(gay.get_name())
# print(len(gay))
# poop = Charmander("poop", 40, "fire", 13,57,55,50)
# poopy = Charmander("poopy", 40, "fire", 15,57,55,50)
# print(poop)
# prop = poop.level_up(10)
# print(prop)


# print(poop)
# print(poop.can_fight())
# print(poop.get_damage(poopy))
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)
# poop.attack(poopy)
# print(poop)
# print(poopy)

#trainer check

#
# # warty = Wartortle("warty", 43, "fire", 27, 65, 73, 90)
# warty = Wartortle("warty", 43, "water", 27, 65, 73, 90)
# pika = Pikachu("pika", 40, "electric", 19, 43, 60, 70, 3)
# print(pika.get_damage(warty))
# print(warty.get_damage(pika))
# ash = Trainer("Ash", 18, 6.0)
# ash.catch_pokemon(pika)
# print(ash)
# misty = Trainer("Misty", 18, 5.5)
# misty.catch_pokemon(warty)
# print(misty)
# print(ash >= misty)
# combined_trainer = ash + misty
# print(combined_trainer)
# charzy = Charizard("charzy", 45, "fire", 36, 80, 99, 85)
# brook = Trainer("Brook", 21, 4.1)
# brook.catch_pokemon(charzy)
# print(brook)
# may = Trainer("May", 22, 7.3)
# may.catch_pokemon(charzy)
# print(may)
# print(may < combined_trainer)
# combined_trainer += may
# print(combined_trainer)
# print(combined_trainer.get_exp_modifier())


#
# pika = Pikachu("pika", 40, "electric", 26, 90, 63, 85, 2)
# blasty = Blastoise("blasty", 43, "water", 37, 82, 93, 113)
# ash = Trainer("ash", 18, 6.0, [pika])
# misty = Trainer("misty", 18, 5.5, [blasty])
# print(ash)
# print(misty)
# battle = Battle(ash, misty)
# battle_score = battle.dual_battle(0, 0)
# print(battle_score)
# print(ash)
# print(misty)

#
# charzy = Charizard("charzy", 45, "fire", 37, 93, 93, 82)
# pika = Pikachu("pika", 40, "electric", 32, 35, 60, 40, 2)
# ash = Trainer("ash", 18, 6.0, [charzy, pika])
# print(ash)
# warty = Wartortle("warty", 43, "water", 30, 78, 80, 93)
# charmy = Charmander("charmy", 41, "fire", 15, 57, 63, 44)
# misty = Trainer("misty", 18, 5.5, [warty, charmy])
# print(misty)
# battle = Battle(ash, misty)
# battle.total_battle()
# print(misty)
# print(ash)
# print(charzy)
# print(pika)
# ash = Trainer("ash", 18, 6.0, [pika, charzy])
# misty = Trainer("misty", 18, 5.5, [warty, charmy])
# print(misty)
# battle = Battle(ash, misty)
# battle.total_battle()
# print(misty)
# print(ash)
# print(charzy)
# ash = Trainer("ash", 18, 6.0, [pika, charzy])
# misty = Trainer("misty", 18, 5.5, [charmy, warty])
# battle = Battle(misty, ash)
# battle.total_battle()
# print(misty)
# print(ash)

charmilious = Charmeleon("charmilious", 42, "fire", 19, 60, 71, 68)
warty = Wartortle("warty", 43, "water", 30, 78, 80, 93)
pika = Pikachu("pika", 40, "electric", 32, 35, 60, 40, 2)
charzy = Charizard("charzy", 45, "fire", 35, 95, 94, 83)
ash = Trainer("ash", 18, 6.0, [charmilious, warty, pika, charzy])
charizardious = Charizard("charizardious", 45, "fire", 37, 93, 93,
82)
squirtly = Squirtle("squirtly", 41, "water", 9, 55, 49, 72)
blasty = Blastoise("blasty", 43, "water", 37, 82, 93, 113)
charmy = Charmander("charmy", 41, "fire", 15, 57, 63, 44)
misty = Trainer("misty", 18, 5.5, [charizardious, squirtly, blasty, charmy])
battle = Battle(misty, ash)
battle.total_battle()
print(misty)
print(ash)
ash = Trainer("ash", 18, 6.0, [charmilious, warty, pika, charzy])
misty = Trainer("misty", 18, 5.5, [charizardious, squirtly,
blasty, charmy])
battle = Battle(ash, misty)
battle.total_battle()
print(misty)
print(ash)
